from enum import StrEnum


class RiskReason(StrEnum):
    """风险过滤或归零原因枚举"""

    NO_DIRECTION = "NO_DIRECTION"
    VOL_RATIO = "VOL_RATIO"
    MIN_POS = "MIN_POS"
    VOTE_FILTER = "VOTE_FILTER"
    FUNDING_CONFLICT = "FUNDING_CONFLICT"
    CONFLICT_FILTER = "CONFLICT_FILTER"
    VOTE_PENALTY = "VOTE_PENALTY"
    FUNDING_PENALTY = "FUNDING_PENALTY"
    CONFLICT_PENALTY = "CONFLICT_PENALTY"
    CROWDING_FILTER = "CROWDING_FILTER"
    CROWDING_PENALTY = "CROWDING_PENALTY"
    RISK_LIMIT = "RISK_LIMIT"
    OI_OVERHEAT = "OI_OVERHEAT"


# 旧名称的兼容别名
ZeroReason = RiskReason

__all__ = ["RiskReason", "ZeroReason"]
