binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

coingecko:
  api_key: "${COINGECKO_API_KEY}"  # 可为空或填写公共 API 密钥

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["5m", "15m", "4h", "d1"]   # 辅助周期K线
  start:  "2024-06-09" # 起始日期 例如"2024-06-01" 默认获取一年
  end:     # 结束日期
  cache_dir: "quant_trade/data/klines"
  sentiment_cache: "quant_trade/data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: ["BUSDT","NEIROETHUSDT"]

feature_engineering:
  cache_dir: "quant_trade/data/klines"
  merged_dir: "quant_trade/data/merged"
  merged_table_path: "quant_trade/data/merged/merged_table.csv"
  feature_cols_path: "quant_trade/data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: quant_trade/scalers/all_features_scaler.json
  btc_symbol: "BTCUSDT"
  eth_symbol: "ETHUSDT"

feature_selector:
  target:
    - target_1h
    - future_volatility_1h
    - future_max_rise_1h
    - future_max_drawdown_1h
    - target_4h
    - future_volatility_4h
    - future_max_rise_4h
    - future_max_drawdown_4h
    - target_d1
    - future_volatility_d1
    - future_max_rise_d1
    - future_max_drawdown_d1
  top_n: 100             # 每周期保留前 N

models:
  1h:
    cls: quant_trade/models/model_1h_cls.pkl
    vol: quant_trade/models/model_1h_vol.pkl
    rise: quant_trade/models/model_1h_rise.pkl
    drawdown: quant_trade/models/model_1h_drawdown.pkl
  4h:
    cls: quant_trade/models/model_4h_cls.pkl
    vol: quant_trade/models/model_4h_vol.pkl
    rise: quant_trade/models/model_4h_rise.pkl
    drawdown: quant_trade/models/model_4h_drawdown.pkl
  d1:
    cls: quant_trade/models/model_d1_cls.pkl
    vol: quant_trade/models/model_d1_vol.pkl
    rise: quant_trade/models/model_d1_rise.pkl
    drawdown: quant_trade/models/model_d1_drawdown.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    cls:
      - atr_pct_1h
      - hv_7d_1h
      - long_lower_shadow_1h
      - long_upper_shadow_1h
      - day_of_week
      - hour_of_day
      - vol_breakout_1h
      - ma_ratio_1h_d1
      - donchian_delta_1h
      - macd_hist_diff_1h_d1
      - rsi_diff_1h_d1
      - atr_pct_ratio_1h_4h

    vol:
      - atr_pct_1h
      - hv_7d_1h
      - vol_ma_ratio_long_1h
      - vol_breakout_1h
      - cg_total_volume_roc_1h
      - hv_30d_1h
      - day_of_week
      - ma_ratio_1h_d1
      - hour_of_day
      - btc_correlation_1h_1h
      - atr_pct_ratio_1h_4h
      - donchian_delta_1h

    rise:
      - atr_pct_1h
      - hv_7d_1h
      - long_lower_shadow_1h
      - donchian_delta_1h
      - macd_hist_diff_1h_d1
      - rsi_diff_1h_d1
      - bull_streak_1h
      - ma_ratio_1h_d1
      - pct_chg6_1h
      - hour_of_day
      - hv_14d_1h
      - ma_ratio_1h_4h

    drawdown:
      - atr_pct_1h
      - hv_7d_1h
      - long_upper_shadow_1h
      - bear_streak_1h
      - donchian_delta_1h
      - macd_hist_diff_1h_d1
      - rsi_diff_1h_d1
      - ma_ratio_1h_d1
      - day_of_week
      - vol_breakout_1h
      - hv_14d_1h
      - ma_ratio_1h_4h

  4h:
    cls:
      - atr_pct_4h
      - hv_7d_4h
      - long_lower_shadow_4h
      - long_upper_shadow_4h
      - day_of_week
      - hour_of_day
      - rsi_diff_4h_d1
      - atr_pct_ratio_1h_4h
      - donchian_delta_4h
      - vol_ratio_4h_d1
      - close_spread_1h_4h
      - vol_ratio_1h_4h
      - hv_14d_4h
      - pct_chg6_4h

    vol:
      - atr_pct_4h
      - hv_7d_4h
      - vol_breakout_4h
      - hv_30d_4h
      - cg_total_volume_roc_4h
      - hour_of_day
      - day_of_week
      - vol_ratio_4h_d1
      - ma_ratio_4h_d1
      - price_ratio_cg_4h
      - atr_pct_ratio_1h_4h
      - rsi_diff_4h_d1

    rise:
      - atr_pct_4h
      - hv_7d_4h
      - long_lower_shadow_4h
      - donchian_delta_4h
      - rsi_diff_4h_d1
      - pct_chg6_4h
      - close_spread_1h_4h
      - hour_of_day
      - vol_ratio_4h_d1
      - day_of_week
      - atr_pct_ratio_1h_4h
      - vol_ratio_1h_4h

    drawdown:
      - atr_pct_4h
      - hv_7d_4h
      - long_upper_shadow_4h
      - donchian_delta_4h
      - hv_14d_4h
      - rsi_diff_4h_d1
      - day_of_week
      - hour_of_day
      - stoch_d_4h
      - kurtosis_4h
      - atr_pct_ratio_1h_4h
      - vol_ratio_1h_4h

  d1:
    cls:
      - day_of_week
      - fg_index_d1_y
      - close_spread_1h_d1
      - vol_ma_ratio_long_d1
      - hv_7d_d1
      - ema_diff_d1
      - vol_ratio_4h_d1
      - pct_chg3_d1
      - kc_width_pct_chg_d1
      - ichimoku_cloud_thickness_d1
      - bb_width_chg_d1
      - cg_total_volume_roc_d1
      - cg_market_cap_roc_d1

    vol:
      - day_of_week
      - vol_ma_ratio_long_d1
      - cg_total_volume_roc_d1
      - hv_7d_d1
      - bb_width_d1
      - atr_chg_d1
      - vol_roc_d1
      - hv_14d_d1
      - rsi_diff_4h_d1
      - vol_ratio_4h_d1
      - obv_delta_d1
      - bb_width_chg_d1
      - cg_market_cap_roc_d1

    rise:
      - day_of_week
      - fg_index_d1_y
      - pct_chg3_d1
      - hv_7d_d1
      - rsi_diff_4h_d1
      - ichimoku_cloud_thickness_d1
      - ema_diff_d1
      - bear_streak_d1
      - obv_delta_d1
      - donchian_delta_d1
      - close_spread_1h_d1
      - vol_ma_ratio_long_d1
      - rsi_diff_1h_d1
      - bb_width_chg_d1

    drawdown:
      - day_of_week
      - fg_index_d1_y
      - hv_14d_d1
      - bb_width_chg_d1
      - vol_ma_ratio_long_d1
      - lower_wick_ratio_d1
      - rsi_diff_1h_d1
      - rsi_diff_4h_d1
      - hv_7d_d1
      - atr_pct_d1
      - close_spread_1h_d1
      - ema_diff_d1
      - cg_total_volume_roc_d1
      - cg_market_cap_roc_d1


train_settings:
  by_symbol: false
  min_rows: 500
  min_samples: 2000
  time_ranges: []
  ts_smote: false
  hold_days: 7
  periods: ["1h", "4h","d1"]       # 例: ["4h", "d1"] 为空则训练全部
  tags: []          # 例: ["up", "down"] 为空则训练全部
  n_trials:
    1h: 15
    4h: 15
    d1: 20

param_space:
  1h:
    lr: [0.03, 0.08]
    nl: [31, 95]
    ne: [400, 800]
    md: [4, 12]
    mcs: [50, 150]
    subsample: [0.8, 1.0]
    cbt: [0.6, 0.9]
    lambda_l2: [0.0, 0.5]
    scale_pos_weight: [1.1, 1.5]
  4h:
    lr:   [0.02, 0.06]     # 学习率保持
    nl:   [31, 127]
    ne:   [140, 260]       # ← 原 300-700，减小以防过拟
    md:   [4, 10]
    mcs:  [1500, 3000]     # ← 原 50-120，增大叶子样本
    subsample: [0.70, 0.9]
    cbt:  [0.45, 0.60]     # = feature_fraction，原 0.6-0.9
    lambda_l2: [4.0, 8.0]  # 原 0.5-4.0，正则更强
    scale_pos_weight: [1.1, 1.5]
  d1:
    lr: [0.02, 0.06]
    nl: [64, 128]
    ne: [180, 260]
    md: [4, 10]
    mcs: [400, 800]
    subsample: [0.75, 0.9]
    cbt: [0.50, 0.65]          # feature_fraction
    lambda_l2: [2.0, 6.0]
    scale_pos_weight: [4, 8]   # 让 Optuna 一起调

fixed_params:
  objective:
    cls: "multiclass"
    vol: "regression"
    rise: "regression"
    drawdown: "regression"
  metric:
    cls: "multi_logloss"
    vol: "l1"
    rise: "l1"
    drawdown: "l1"
  lambda_l2: 2.0
  early_stopping_rounds: 40
  n_jobs: -1

model_params:
  1h:                       # ≈55 万行
    num_boost_round: 600
    min_data_in_leaf: 700
    feature_fraction: 0.80
    bagging_fraction: 0.80
    bagging_freq: 1
  4h:                       # ≈13 万行
    num_boost_round: 140      # ← 原 160
    min_data_in_leaf: 2200    # 不变
    feature_fraction: 0.48    # ← 原 0.50
    lambda_l2: 7.0            # ← 原 6.0
    bagging_fraction: 0.70
    bagging_freq: 1
  d1:                       # ≈2.2 万行
    num_boost_round: 260
    min_data_in_leaf: 600
    feature_fraction: 0.58
    bagging_fraction: 0.80
    bagging_freq: 1
    lambda_l2: 5.0            # ★ 新增，固定 L2
    scale_pos_weight: 6       # ★ 新增，补偿空头稀缺

# Δ-boost 配置：关键指标与参数
delta_boost:
  core_keys:
    "1h":
      - rsi_1h
      - macd_hist_1h
      - ema_diff_1h
      - atr_pct_1h
      - vol_ma_ratio_long_1h
      - funding_rate_1h
    "4h":
      - rsi_4h
      - macd_hist_4h
      - ema_diff_4h
    d1:
      - rsi_d1
      - macd_hist_d1
      - ema_diff_d1
  params:
    rsi: [5, 1.0, 0.05]
    macd_hist: [0.002, 100.0, 0.05]
    ema_diff: [0.001, 100.0, 0.03]
    atr_pct: [0.002, 100.0, 0.03]
    vol_ma_ratio: [0.2, 1.0, 0.03]
    funding_rate: [0.0005, 10000, 0.03]


vote_system:
  weight_ai: 3
  strong_min: 3
  conf_min: 0.25
  ai_dir_eps: 0.04
vote_weights:
  ob: 4
  short_mom: 2
  ai: 3
  vol_breakout: 1

# === 调参选项 ===
sentiment_alpha: 0.5
cap_positive_scale: 0.85
volume_guard:
  weak_scale: 0.85
  over_scale: 0.9
  ratio_low: 0.6
  ratio_high: 2.0
  roc_low: -20
  roc_high: 100
ob_threshold:
  min_ob_th: 0.10
  dynamic_factor: 0.08
risk_score_cap: 5.0
exit_lag_bars: 1
# quantile: 0.88
signal_filters:
  confidence_vote: 0.33
  ob_th_min: 0.10
  require_strong_confirm_4h: false
oi_protection:
  scale: 0.9
  crowding_threshold: 0.90
veto_level: 0.9
flip_coeff: 0.8
th_down_d1: 0.74  # d1空头AI模型阈值，后续可灵活调整
position_coeff:
  range: 0.40
  trend: 0.60
signal_threshold:
  # mode: sigmoid      # 可选：sigmoid / double
  base_th: 0.09343      # 原 dynamic_th_final 的初始值
  gamma: 0.05        # 过渡宽度
  min_pos: 0.10      # pos_size < 0.10 则 direction = 0
  low_base: 0.06
  # base_th / low_base 单位为 fused_score
  rev_boost: 0.30      # detect_reversal 命中时加分
  rev_th_mult: 0.60    # 急反转时降低门槛

# 因子 IC 分数更新设置
ic_update_rows: 3000          # 从 features 表读取的记录数
ic_update_interval_hours: 24  # 多少小时刷新一次权重，默认为每日
ic_scores:
  1h: 1.0
  4h: 0.2
  d1: 0.1
