-- ───────── klines 完整建表语句 ─────────
CREATE TABLE klines (
    -- 基础信息
    symbol             VARCHAR(20)     NOT NULL,
    `interval`         VARCHAR(10)     NOT NULL,
    open_time          DATETIME(3)     NOT NULL,
    close_time         DATETIME(3)     NOT NULL,

    -- 原生 K 线
    `open`             DOUBLE,
    high               DOUBLE,
    low                DOUBLE,
    `close`            DOUBLE,
    volume             DOUBLE,
    quote_asset_volume DOUBLE,
    num_trades         INT,
    taker_buy_base     DOUBLE,
    taker_buy_quote    DOUBLE,

    -- 情绪 & 资金费率
    fg_index           DOUBLE  NULL,
    funding_rate       DOUBLE  NULL,
    cg_price           DOUBLE,
    cg_market_cap      DOUBLE,
    cg_total_volume    DOUBLE,

    -- 索引
    PRIMARY KEY (symbol, `interval`, open_time),
    INDEX idx_symbol_interval_time (symbol, `interval`, open_time),
    INDEX idx_open_time (open_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE sentiment (
    timestamp              BIGINT UNSIGNED NOT NULL PRIMARY KEY,  -- UTC 秒
    value                  VARCHAR(10),
    value_classification   VARCHAR(32),
    fg_index               DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE funding_rate (
    symbol          VARCHAR(32) NOT NULL,
    fundingTime     DATETIME    NOT NULL,
    fundingRate     DOUBLE      NOT NULL,
    PRIMARY KEY (symbol, fundingTime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 持仓量表：open_interest
CREATE TABLE open_interest (
    symbol        VARCHAR(20)  NOT NULL,
    timestamp     DATETIME(3)  NOT NULL,
    open_interest DOUBLE,
    PRIMARY KEY (symbol, timestamp),
    INDEX idx_timestamp (timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cg_market_data (
    symbol VARCHAR(20) NOT NULL,
    timestamp DATETIME(3) NOT NULL,
    price DOUBLE,
    market_cap DOUBLE,
    total_volume DOUBLE,
    PRIMARY KEY (symbol, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cg_global_metrics (
    timestamp DATETIME(3) NOT NULL PRIMARY KEY,
    total_market_cap DOUBLE,
    total_volume DOUBLE,
    btc_dominance DOUBLE,
    eth_dominance DOUBLE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cg_coin_categories (
    symbol VARCHAR(20) NOT NULL PRIMARY KEY,
    categories TEXT,
    last_updated DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE cg_category_stats (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    name VARCHAR(64),
    market_cap DOUBLE,
    market_cap_change_24h DOUBLE,
    volume_24h DOUBLE,
    top_3_coins TEXT,
    updated_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `features` (
    `symbol` VARCHAR(24) NOT NULL,
    `open_time` DATETIME,
    `close_time` DATETIME,
    `quote_asset_volume` DOUBLE,
    `num_trades` DOUBLE,
    `taker_buy_base` DOUBLE,
    `taker_buy_quote` DOUBLE,
    `interval` VARCHAR(8) DEFAULT '1h',
    `open` DOUBLE,
    `high` DOUBLE,
    `low` DOUBLE,
    `close` DOUBLE,
    `volume` DOUBLE,
    `fg_index` DOUBLE,
    `funding_rate` DOUBLE,
    `adx_1h` DOUBLE,
    `adx_4h` DOUBLE,
    `adx_d1` DOUBLE,
    `adx_delta_1h` DOUBLE,
    `adx_delta_4h` DOUBLE,
    `adx_delta_d1` DOUBLE,
    `atr_chg_1h` DOUBLE,
    `atr_chg_4h` DOUBLE,
    `atr_chg_d1` DOUBLE,
    `atr_pct_1h` DOUBLE,
    `atr_pct_4h` DOUBLE,
    `atr_pct_d1` DOUBLE,
    `atr_pct_ratio_1h_4h` DOUBLE,
    `bb_width_1h` DOUBLE,
    `bb_width_4h` DOUBLE,
    `bb_width_chg_1h` DOUBLE,
    `bb_width_chg_4h` DOUBLE,
    `bb_width_chg_d1` DOUBLE,
    `bb_width_d1` DOUBLE,
    `bb_width_ratio_1h_4h` DOUBLE,
    `bear_streak_1h` DOUBLE,
    `bear_streak_4h` DOUBLE,
    `bear_streak_d1` DOUBLE,
    `bid_ask_spread_pct_1h` DOUBLE,
    `bid_ask_spread_pct_4h` DOUBLE,
    `bid_ask_spread_pct_d1` DOUBLE,
    `body_ratio_1h` DOUBLE,
    `body_ratio_4h` DOUBLE,
    `body_ratio_d1` DOUBLE,
    `boll_perc_1h` DOUBLE,
    `boll_perc_4h` DOUBLE,
    `boll_perc_d1` DOUBLE,
    `bull_streak_1h` DOUBLE,
    `bull_streak_4h` DOUBLE,
    `bull_streak_d1` DOUBLE,
    `buy_sell_ratio_1h` DOUBLE,
    `buy_sell_ratio_4h` DOUBLE,
    `buy_sell_ratio_d1` DOUBLE,
    `cci_1h` DOUBLE,
    `cci_4h` DOUBLE,
    `cci_d1` DOUBLE,
    `cci_delta_1h` DOUBLE,
    `cci_delta_4h` DOUBLE,
    `cci_delta_d1` DOUBLE,
    `cg_market_cap` DOUBLE,
    `cg_market_cap_roc_1h` DOUBLE,
    `cg_market_cap_roc_4h` DOUBLE,
    `cg_market_cap_roc_d1` DOUBLE,
    `cg_price` DOUBLE,
    `cg_total_volume` DOUBLE,
    `cg_total_volume_roc_1h` DOUBLE,
    `cg_total_volume_roc_4h` DOUBLE,
    `cg_total_volume_roc_d1` DOUBLE,
    `close_1h` DOUBLE,
    `close_4h` DOUBLE,
    `close_d1` DOUBLE,
    `close_spread_1h_4h` DOUBLE,
    `close_spread_1h_d1` DOUBLE,
    `close_time_4h` DOUBLE,
    `close_time_d1` DOUBLE,
    `day_of_week` DOUBLE,
    `donchian_delta_1h` DOUBLE,
    `donchian_delta_4h` DOUBLE,
    `donchian_delta_d1` DOUBLE,
    `donchian_perc_1h` DOUBLE,
    `donchian_perc_4h` DOUBLE,
    `donchian_perc_d1` DOUBLE,
    `ema_diff_1h` DOUBLE,
    `ema_diff_4h` DOUBLE,
    `ema_diff_d1` DOUBLE,
    `fg_index_feat` DOUBLE,
    `fg_index_x` DOUBLE,
    `fg_index_y` DOUBLE,
    `funding_rate_anom_1h` DOUBLE,
    `funding_rate_anom_4h` DOUBLE,
    `funding_rate_anom_d1` DOUBLE,
    `funding_rate_feat` DOUBLE,
    `funding_rate_x` DOUBLE,
    `funding_rate_y` DOUBLE,
    `future_max_drawdown` DOUBLE,
    `future_max_rise` DOUBLE,
    `future_volatility` DOUBLE,
    `high_feat` DOUBLE,
    `high_x` DOUBLE,
    `high_y` DOUBLE,
    `hour_of_day` DOUBLE,
    `hv_14d_1h` DOUBLE,
    `hv_14d_4h` DOUBLE,
    `hv_14d_d1` DOUBLE,
    `hv_30d_1h` DOUBLE,
    `hv_30d_4h` DOUBLE,
    `hv_30d_d1` DOUBLE,
    `hv_7d_1h` DOUBLE,
    `hv_7d_4h` DOUBLE,
    `hv_7d_d1` DOUBLE,
    `ichimoku_base_1h` DOUBLE,
    `ichimoku_base_4h` DOUBLE,
    `ichimoku_base_d1` DOUBLE,
    `ichimoku_cloud_thickness_1h` DOUBLE,
    `ichimoku_cloud_thickness_4h` DOUBLE,
    `ichimoku_cloud_thickness_d1` DOUBLE,
    `ichimoku_conversion_1h` DOUBLE,
    `ichimoku_conversion_4h` DOUBLE,
    `ichimoku_conversion_d1` DOUBLE,
    `kc_perc_1h` DOUBLE,
    `kc_perc_4h` DOUBLE,
    `kc_perc_d1` DOUBLE,
    `kc_width_pct_chg_1h` DOUBLE,
    `kc_width_pct_chg_4h` DOUBLE,
    `kc_width_pct_chg_d1` DOUBLE,
    `kurtosis_1h` DOUBLE,
    `kurtosis_4h` DOUBLE,
    `kurtosis_d1` DOUBLE,
    `long_lower_shadow_1h` DOUBLE,
    `long_lower_shadow_4h` DOUBLE,
    `long_lower_shadow_d1` DOUBLE,
    `long_upper_shadow_1h` DOUBLE,
    `long_upper_shadow_4h` DOUBLE,
    `long_upper_shadow_d1` DOUBLE,
    `low_feat` DOUBLE,
    `low_x` DOUBLE,
    `low_y` DOUBLE,
    `lower_wick_ratio_1h` DOUBLE,
    `lower_wick_ratio_4h` DOUBLE,
    `lower_wick_ratio_d1` DOUBLE,
    `ma_ratio_1h_4h` DOUBLE,
    `ma_ratio_1h_d1` DOUBLE,
    `macd_1h` DOUBLE,
    `macd_4h` DOUBLE,
    `macd_d1` DOUBLE,
    `macd_hist_1h` DOUBLE,
    `macd_hist_1h_mul_bb_width_4h` DOUBLE,
    `macd_hist_4h` DOUBLE,
    `macd_hist_4h_mul_bb_width_1h` DOUBLE,
    `macd_hist_d1` DOUBLE,
    `macd_hist_diff_1h_4h` DOUBLE,
    `macd_hist_diff_1h_d1` DOUBLE,
    `macd_signal_1h` DOUBLE,
    `macd_signal_4h` DOUBLE,
    `macd_signal_d1` DOUBLE,
    `mfi_1h` DOUBLE,
    `mfi_4h` DOUBLE,
    `mfi_d1` DOUBLE,
    `money_flow_ratio_1h` DOUBLE,
    `money_flow_ratio_4h` DOUBLE,
    `money_flow_ratio_d1` DOUBLE,
    `obv_1h` DOUBLE,
    `obv_4h` DOUBLE,
    `obv_d1` DOUBLE,
    `obv_delta_1h` DOUBLE,
    `obv_delta_4h` DOUBLE,
    `obv_delta_d1` DOUBLE,
    `open_feat` DOUBLE,
    `open_x` DOUBLE,
    `open_y` DOUBLE,
    `pct_chg1_1h` DOUBLE,
    `pct_chg1_4h` DOUBLE,
    `pct_chg1_d1` DOUBLE,
    `pct_chg3_1h` DOUBLE,
    `pct_chg3_4h` DOUBLE,
    `pct_chg3_d1` DOUBLE,
    `pct_chg6_1h` DOUBLE,
    `pct_chg6_4h` DOUBLE,
    `pct_chg6_d1` DOUBLE,
    `mom_5m_roll1h` DOUBLE,
    `mom_5m_roll1h_std` DOUBLE,
    `mom_15m_roll1h` DOUBLE,
    `mom_15m_roll1h_std` DOUBLE,
    `price_diff_cg_1h` DOUBLE,
    `price_diff_cg_4h` DOUBLE,
    `price_diff_cg_d1` DOUBLE,
    `price_ratio_cg_1h` DOUBLE,
    `price_ratio_cg_4h` DOUBLE,
    `price_ratio_cg_d1` DOUBLE,
    `rsi_1h` DOUBLE,
    `rsi_1h_mul_vol_ma_ratio_4h` DOUBLE,
    `rsi_4h` DOUBLE,
    `rsi_d1` DOUBLE,
    `rsi_diff_1h_4h` DOUBLE,
    `rsi_diff_1h_d1` DOUBLE,
    `rsi_mul_vol_ma_ratio_1h` DOUBLE,
    `rsi_mul_vol_ma_ratio_4h` DOUBLE,
    `rsi_mul_vol_ma_ratio_d1` DOUBLE,
    `rsi_slope_1h` DOUBLE,
    `rsi_slope_4h` DOUBLE,
    `rsi_slope_d1` DOUBLE,
    `skewness_1h` DOUBLE,
    `skewness_4h` DOUBLE,
    `skewness_d1` DOUBLE,
    `sma_10_1h` DOUBLE,
    `sma_10_4h` DOUBLE,
    `sma_10_d1` DOUBLE,
    `supertrend_dir_1h` DOUBLE,
    `supertrend_dir_4h` DOUBLE,
    `supertrend_dir_d1` DOUBLE,
    `upper_wick_ratio_1h` DOUBLE,
    `upper_wick_ratio_4h` DOUBLE,
    `upper_wick_ratio_d1` DOUBLE,
    `vol_breakout_1h` DOUBLE,
    `vol_breakout_4h` DOUBLE,
    `vol_breakout_d1` DOUBLE,
    `vol_ma_ratio_1h` DOUBLE,
    `vol_ma_ratio_4h` DOUBLE,
    `vol_ma_ratio_d1` DOUBLE,
    `vol_ma_ratio_long_1h` DOUBLE,
    `vol_ma_ratio_long_4h` DOUBLE,
    `vol_ma_ratio_long_d1` DOUBLE,
    `vol_profile_density_1h` DOUBLE,
    `vol_profile_density_4h` DOUBLE,
    `vol_profile_density_d1` DOUBLE,
    `vol_roc_1h` DOUBLE,
    `vol_roc_4h` DOUBLE,
    `vol_roc_d1` DOUBLE,
    `volume_cg_ratio_1h` DOUBLE,
    `volume_cg_ratio_4h` DOUBLE,
    `volume_cg_ratio_d1` DOUBLE,
    `volume_feat` DOUBLE,
    `volume_x` DOUBLE,
    `volume_y` DOUBLE,
    `willr_1h` DOUBLE,
    `willr_4h` DOUBLE,
    `willr_d1` DOUBLE,
    PRIMARY KEY (`symbol`, `open_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `live_full_data` (
    `symbol`      VARCHAR(24) NOT NULL,
    `time`        DATETIME NOT NULL,
    `price`       DOUBLE,
    `signal`      TINYINT,
    `score`       DOUBLE,
    `pos`         DOUBLE,
    `take_profit` DOUBLE NULL,
    `stop_loss`   DOUBLE NULL,
    `indicators`  JSON,      -- 也可使用 TEXT 类型
    PRIMARY KEY (`symbol`, `time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `live_top10_signals` (
    `symbol` VARCHAR(24) NOT NULL,
    `time` DATETIME NOT NULL,
    `price` DOUBLE,
    `signal` TINYINT,
    `score` DOUBLE,
    `pos` DOUBLE,
    `take_profit` DOUBLE NULL,
    `stop_loss` DOUBLE NULL,
    `indicators`  JSON,      -- 也可使用 TEXT 类型
    PRIMARY KEY (`symbol`, `time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

TRUNCATE TABLE klines;
TRUNCATE TABLE sentiment;
TRUNCATE TABLE funding_rate;
TRUNCATE TABLE open_interest;
TRUNCATE TABLE cg_market_data;
TRUNCATE TABLE cg_global_metrics;
TRUNCATE TABLE cg_coin_categories;
TRUNCATE TABLE features;
TRUNCATE TABLE live_full_data;
TRUNCATE TABLE live_top10_signals;
