w_ai_1h: 1.0
w_ai_4h: 1.0
w_ai_d1: 1.0
w_factor:
  trend: 1.0
  momentum: 1.0
  volatility: 1.0
  volume: 1.0
  sentiment: 1.0
  funding: 1.0
ic_threshold: 0.0
cache:
  factor_maxsize: 300
  ai_maxsize: 300
  ttl: 3600
batch:
  max_workers: 4
fusion:
  min_agree: 2
  conflict_mult: 0.7
  cycle_weight:
    strong: 1.0
    weak: 1.0
    opposite: 1.0
    conflict: 0.7

signal_threshold:
  base_th: 0.1

dynamic_threshold:
  smooth_window: 20
  th_window: 60
  th_decay: 2.0
