binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["4h", "1d"]   # 辅助周期K线
  start: "2024-06-01" # 起始日期
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
  d1:
    up: models/model_d1_up.pkl
    down: models/model_d1_down.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    - hour_of_day
    - fg_index_x            # 情绪，Top2，极端行情捕捉
    - atr_pct_1h            # 波动率，Top4，强泛化能力
    - rsi_mul_vol_ma_ratio_1h # 动量与量能结合，Top10，捕捉异动
    - rsi_slope_1h          # 动量斜率，Top14
    - vol_ma_ratio_1h       # 量能活跃度，Top15
    - cci_delta_1h          # 顺势动量，Top16
  4h:
    - fg_index_x            # 情绪（4h同样有效，Top1）
    - atr_pct_4h            # 波动率，Top11
    - vol_roc_4h            # 量能变化，Top8
    - cci_delta_4h          # 顺势动量，Top29
    - rsi_slope_4h          # 动量斜率，Top31
    - willr_4h              # 超买超卖信号，Top48
  d1:
    - fg_index_x            # 情绪（日线依然有效，Top1）
    - atr_pct_1h            # 短周期波动（日线Top3，适合极端大行情）
    - day_of_week           # 周期性（日线高权重，Top5）
    - cci_delta_1h          # 顺势动量（Top8）
    - adx_4h                # 趋势强度（Top22）
    - bb_width_chg_d1       # 布林带宽变化（日线极端行情，Top30）
