binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

coingecko:
  api_key: "${COINGECKO_API_KEY}"  # 可为空或填写公共 API 密钥

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["5m", "15m", "4h", "1d"]   # 辅助周期K线
  start:  # 起始日期 例如"2024-06-01" 默认获取一年
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
    vol: models/model_1h_vol.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
    vol: models/model_4h_vol.pkl
  d1:
    up: models/model_1d_up.pkl
    down: models/model_1d_down.pkl
    vol: models/model_1d_vol.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    # —— 价格 / 动量 ——
    - pct_chg1_1h                # 1h涨跌幅，最直观的价格动量

    # —— 趋势 / 振荡 ——
    - cci_delta_1h               # CCI变化率，捕捉趋势/拐点

    # —— 波动率 ——
    - hv_14d_1h                  # 14天历史波动率，衡量近期市场波动

    # —— 成交量 / 资金流 ——
    - obv_delta_1h               # OBV变化，量价关系

    # —— K线结构/形态 ——
    - upper_wick_ratio_1h        # 上影线比例，反映抛压/多空力量

    # —— 周期互补 ——
    - close_spread_1h_4h         # 1h与4h收盘价乖离幅度，周期对比

    # —— 衍生/异常值 ——
    - funding_rate_anom_d1       # 1d资金费率异常，捕捉极端风险

    # —— 时序因子 ——
    - hour_of_day                # 日内效应（或者day_of_week，二选一即可）

    # —— 反转与极端 ——
    - kurtosis_1h                # 1h偏度，衡量极端行情

    # —— 趋势计数类 ——
    - bear_streak_1h             # 1h连跌计数，反映趋势强度
  4h:
    # —— 价格 / 动量 ——
    - pct_chg6_4h               # 4h周期累计涨跌幅，更能反映4h动量

    # —— 趋势 / 振荡 ——
    - rsi_slope_4h              # 4h RSI斜率，反映趋势转折或持续

    # —— 波动率 ——
    - hv_14d_1h                 # 14天历史波动率（1h窗口，4h行情一般也适用）

    # —— 成交量 / 资金流 ——
    - vol_roc_4h                # 4h成交量变化，代表4h内资金异动

    # —— K线结构/形态 ——
    - upper_wick_ratio_4h       # 4h上影线，反映中线抛压或结构

    # —— 周期互补 ——
    - pct_chg1_1h               # 1h涨跌幅，和4h周期互补，防止只看一头

    # —— 衍生/异常值 ——
    - funding_rate_anom_d1      # 1d资金费率异常，捕捉极端行情/风险

    # —— 时序因子 ——
    - day_of_week               # 周内效应（或者hour_of_day，二选一，4h建议用day_of_week）

    # —— 反转与极端 ——
    - kurtosis_1h               # 1h偏度，补充极端行情过滤

    # —— 趋势计数类 ——
    - bear_streak_4h            # 4h连跌计数，衡量4h趋势强度
  1d:
    # —— 价格 / 动量 ——
    - pct_chg1_1h                # 1h涨跌幅

    # —— 趋势 / 振荡 ——
    - macd_signal_d1             # 1d MACD信号

    # —— 波动率 ——
    - hv_30d_1h                  # 1h的30天历史波动率

    # —— 成交量 / 资金流 ——
    - obv_delta_1h               # 1h OBV变化

    # —— K线结构/形态 ——
    - upper_wick_ratio_1h        # 1h上影线比例

    # —— 周期互补 ——
    - upper_wick_ratio_4h        # 4h上影线比例

    # —— 衍生指标/异常值 ——
    - funding_rate_anom_d1       # 1d资金费率异常

    # —— 时序因子 ——
    - day_of_week                # 周内效应

    # —— 反转与极端 ——
    - kurtosis_1h                # 1h偏度

    # —— 趋势计数类 ——
    - bear_streak_1h             # 1h连跌计数


train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
  ts_smote: true

