binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["4h", "1d"]   # 辅助周期K线
  start: "2024-06-01" # 起始日期
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
    vol: models/model_1h_vol.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
    vol: models/model_4h_vol.pkl
  d1:
    up: models/model_1d_up.pkl
    down: models/model_1d_down.pkl
    vol: models/model_1d_vol.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1d:
    # 日线自身动量、波动与跨周期关键信号
    - atr_pct_d1               # 日线波动率
    - pct_chg6_d1             # 日线 6 日动量
    - rsi_slope_d1            # 日线 RSI 斜率
    - cci_delta_d1            # 日线 CCI 变化率
    - vol_roc_d1              # 日线成交量动量
    - vol_ma_ratio_long_d1    # 日线长期成交量比
    # 短中周期信号
    - atr_pct_4h              # 4h 波动率
    - atr_pct_1h              # 1h 波动率
    - pct_chg1_1h             # 1h 短期动量
    - pct_chg3_4h             # 4h 中期动量
    - atr_pct_ratio_1h_4h     # 1h/4h 波动率比
    # 周期与情绪
    - day_of_week             # 星期效应
    - fg_index_feat           # 市场情绪因子
    - funding_rate_anom_d1    # 日线资金费率异动

  4h:
    # 4h 主周期特征
    - atr_pct_4h
    - pct_chg3_4h
    - rsi_slope_4h
    - cci_delta_4h
    - vol_roc_4h
    - vol_ma_ratio_long_4h
    # 跨周期补充
    - atr_pct_ratio_1h_4h
    - rsi_diff_1h_4h
    - atr_pct_d1
    # 形态与情绪
    - body_ratio_4h
    - upper_wick_ratio_4h
    - day_of_week
    - hour_of_day
    - fg_index_feat
    - funding_rate_anom_4h

  1h:
    # 1h 主周期特征
    - atr_pct_1h
    - pct_chg1_1h
    - rsi_slope_1h
    - cci_delta_1h
    - vol_roc_1h
    - vol_ma_ratio_long_1h
    # 跨周期补充
    - atr_pct_4h
    - atr_pct_d1
    - pct_chg6_4h
    - pct_chg6_d1
    # 形态与情绪
    - body_ratio_1h
    - upper_wick_ratio_1h
    - hour_of_day
    - day_of_week
    - fg_index_feat
    - funding_rate_anom_1h

train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
