binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

coingecko:
  api_key: "${COINGECKO_API_KEY}"  # 可为空或填写公共 API 密钥

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["5m", "15m", "4h", "1d"]   # 辅助周期K线
  start:  # 起始日期 例如"2024-06-01" 默认获取一年
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: ["BUSDT"]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json
  btc_symbol: "BTCUSDT"
  eth_symbol: "ETHUSDT"

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
    vol: models/model_1h_vol.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
    vol: models/model_4h_vol.pkl
  d1:
    up: models/model_d1_up.pkl
    down: models/model_d1_down.pkl
    vol: models/model_d1_vol.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:

  1h:            # 43 个  (-2)
    # 动量 / 趋势
    - pct_chg1_1h
    - pct_chg3_1h
    - pct_chg6_1h
    - pct_chg3_4h
    - pct_chg6_4h
    - cci_1h
    - cci_delta_1h
    - macd_hist_1h
    - rsi_diff_1h_4h
    - rsi_slope_4h
    # 波动 / 通道
    - atr_chg_1h
    - atr_pct_ratio_1h_4h
    - bb_width_chg_1h
    - bb_width_ratio_1h_4h
    - hv_7d_1h
    - hv_14d_d1
    # 形态
    - upper_wick_ratio_1h
    - lower_wick_ratio_1h
    - long_upper_shadow_1h
    - long_lower_shadow_1h
    - bear_streak_1h
    - bull_streak_1h
    - close_spread_1h_4h
    - lower_wick_ratio_4h
    # 量价 / 资金
    - vol_ma_ratio_long_1h
    - vol_roc_1h
    - vol_breakout_1h
    - volume_cg_ratio_1h
    - obv_delta_1h
    - vol_profile_density_1h
    - cg_total_volume_roc_1h
    - cg_market_cap_roc_1h
    # 宏观 / 相关
    - fg_index_d1
    - btc_correlation_1h_1h
    - eth_correlation_1h_1h
    - cg_market_cap_roc_d1
    - donchian_perc_d1
    # 时间
    - hour_of_day
    - day_of_week
    # 统计补充
    - kurtosis_1h
    - skewness_1h
    # ⚠ 移除：vol_breakout_4h, atr_chg_d1, vol_breakout_d1

  4h:            # 30 个  (-2 × 1 h 噪声, +1 稳定宏观)
    - pct_chg1_4h
    - pct_chg3_4h
    - pct_chg6_4h
    - rsi_slope_4h
    - rsi_diff_1h_4h
    - macd_hist_diff_1h_d1
    - cci_delta_4h
    - cci_1h
    - cci_delta_1h
    - atr_chg_4h
    - atr_pct_ratio_1h_4h
    - bb_width_chg_4h
    - bb_width_ratio_1h_4h
    - hv_7d_4h
    - upper_wick_ratio_4h
    - lower_wick_ratio_4h
    - long_lower_shadow_4h
    - skewness_4h
    - kurtosis_4h
    - vol_ma_ratio_long_1h
    - vol_roc_4h
    - vol_breakout_4h
    - vol_ratio_1h_4h
    - cg_total_volume_roc_4h
    - cg_market_cap_roc_4h        # ← 新增，同族里日线→4 h 更匹配
    - fg_index_d1
    - funding_rate_anom_d1
    - hour_of_day
    - day_of_week
    # ⚠ 移除：pct_chg1_1h, pct_chg3_1h  (高方差 1 h 噪声)

  d1:            # 23 个  (-6 × 1 h, +1 hv_30d_1h 改 hv_30d_d1)
    - pct_chg1_1h            # 保留一个领先动量
    - pct_chg3_1h
    - cci_delta_1h           # 仅留一个 1 h 技术差分
    - cg_market_cap_roc_d1
    - fg_index_d1
    - vol_ma_ratio_long_d1
    - vol_ratio_4h_d1
    - vol_breakout_d1
    - macd_hist_d1
    - ema_diff_d1
    - atr_chg_d1
    - atr_pct_d1
    - kc_width_pct_chg_d1
    - bb_width_chg_d1
    - hv_14d_d1
    - hv_30d_d1              # 用 d1 版，移除 hv_30d_1h
    - rsi_diff_1h_4h
    - upper_wick_ratio_d1
    - lower_wick_ratio_d1
    - skewness_d1
    - kurtosis_d1
    - vol_roc_d1
    - day_of_week
    # ⚠ 移除：bear_streak_1h, hv_30d_1h, atr_chg_4h 及其它 1 h 形态

train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
  ts_smote: true
  ts_smote_group_freq: 1d
  hold_days: 7
  periods: []       # 例: ["4h", "d1"] 为空则训练全部
  tags: []          # 例: ["up", "down"] 为空则训练全部
  n_trials:
    1h: 10
    4h: 10
    d1: 15

param_space:
  1h:
    lr: [0.03, 0.08]
    nl: [31, 95]
    ne: [400, 800]
    md: [4, 12]
    mcs: [50, 150]
    subsample: [0.8, 1.0]
    cbt: [0.6, 0.9]
    reg_lambda: [0.0, 0.5]
  4h:
    lr: [0.02, 0.06]
    nl: [31, 127]
    ne: [300, 700]
    md: [4, 10]
    mcs: [50, 120]
    subsample: [0.8, 1.0]
    cbt: [0.6, 0.9]
    reg_lambda: [0.0, 0.5]
  d1:
    lr: [0.005, 0.03]
    nl: [64, 160]
    ne: [300, 600]
    md: [4, 10]
    mcs: [40, 100]
    subsample: [0.85, 1.0]
    cbt: [0.6, 0.9]
    reg_lambda: [0.0, 0.5]

fixed_params:
  objective:
    up: "binary"
    down: "binary"
    vol: "regression"
  metric:
    up: "auc"
    down: "auc"
    vol: "l1"
  early_stopping_rounds: 40
  n_jobs: -1

model_params:
  1h:                       # ≈55 万行
    num_boost_round: 600
    min_data_in_leaf: 700
    feature_fraction: 0.80
    bagging_fraction: 0.80
    bagging_freq: 1
  4h:                       # ≈13 万行
    num_boost_round: 350
    min_data_in_leaf: 1000
    feature_fraction: 0.75
    bagging_fraction: 0.80
    bagging_freq: 1
  d1:                       # ≈2.2 万行
    num_boost_round: 250
    min_data_in_leaf: 400
    feature_fraction: 0.70
    bagging_fraction: 0.80
    bagging_freq: 1

# Δ-boost 配置：关键指标与参数
delta_boost:
  core_keys:
    "1h":
      - rsi_1h
      - macd_hist_1h
      - ema_diff_1h
      - atr_pct_1h
      - vol_ma_ratio_long_1h
      - funding_rate_1h
    "4h":
      - rsi_4h
      - macd_hist_4h
      - ema_diff_4h
    d1:
      - rsi_d1
      - macd_hist_d1
      - ema_diff_d1
  params:
    rsi: [5, 1.0, 0.05]
    macd_hist: [0.002, 100.0, 0.05]
    ema_diff: [0.001, 100.0, 0.03]
    atr_pct: [0.002, 100.0, 0.03]
    vol_ma_ratio: [0.2, 1.0, 0.03]
    funding_rate: [0.0005, 10000, 0.03]


vote_system:
  weight_ai: 2.0
  strong_min: 5
  conf_min: 0.40
  ai_dir_eps: 0.02

# === 调参选项 ===
sentiment_alpha: 0.5
cap_positive_scale: 0.7
volume_guard:
  weak_scale: 0.85
  over_scale: 0.9
  ratio_low: 0.6
  ratio_high: 2.0
  roc_low: -20
  roc_high: 100
ob_threshold:
  min_ob_th: 0.15
  dynamic_factor: 0.08
risk_score_cap: 5.0
exit_lag_bars: 1
quantile: 0.88
vote:
  strong_min: 3
  conf_min: 0.25
oi_protection:
  scale: 0.9
  crowding_threshold: 0.90
veto_level: 0.9
flip_coeff: 0.3
position_coeff:
  range: 0.40
  trend: 0.60
signal_threshold:
  mode: sigmoid      # 可选：sigmoid / double
  base_th: 0.12      # 原 dynamic_th_final 的初始值
  gamma: 0.05        # 过渡宽度
  min_pos: 0.10      # pos_size < 0.10 则 direction = 0
  low_base: 0.10
