binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["4h", "1d"]   # 辅助周期K线
  start: "2024-06-01" # 起始日期
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
  d1:
    up: models/model_1d_up.pkl
    down: models/model_1d_down.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    - atr_pct_1h
    - pct_chg1_1h
    - rsi_slope_1h
    - cci_delta_1h
    - vol_roc_1h
    - ma_ratio_1h_4h
    - upper_wick_ratio_1h
    - body_ratio_1h
    - vol_ma_ratio_1h
    - fg_index_feat
    - adx_1h
    - boll_perc_1h
    - funding_rate_anom_1h
    - donchian_perc_1h
    - rsi_diff_1h_4h
    - obv_delta_1h
    - mfi_1h
    - atr_chg_1h
    - vol_ma_ratio_long_1h
    - pct_chg6_1h

  4h:
    - atr_pct_4h
    - pct_chg3_4h
    - rsi_slope_4h
    - cci_delta_4h
    - vol_roc_4h
    - ma_ratio_1h_4h
    - upper_wick_ratio_4h
    - body_ratio_4h
    - vol_ma_ratio_4h
    - fg_index_feat
    - adx_4h
    - boll_perc_4h
    - funding_rate_anom_4h
    - donchian_perc_4h
    - rsi_diff_1h_4h
    - obv_delta_4h
    - mfi_4h
    - atr_chg_4h
    - vol_ma_ratio_long_4h
    - pct_chg6_4h

  1d:
    - atr_pct_d1
    - pct_chg3_d1
    - rsi_slope_d1
    - cci_delta_d1
    - vol_roc_d1
    - ma_ratio_1h_d1
    - upper_wick_ratio_d1
    - body_ratio_d1
    - vol_ma_ratio_d1
    - fg_index_feat
    - adx_d1
    - boll_perc_d1
    - funding_rate_anom_d1
    - donchian_perc_d1
    - rsi_diff_1h_d1
    - obv_delta_d1
    - mfi_d1
    - atr_chg_d1
    - vol_ma_ratio_long_d1
    - pct_chg6_d1

train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
