binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

coingecko:
  api_key: "${COINGECKO_API_KEY}"  # 可为空或填写公共 API 密钥

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["5m", "15m", "4h", "1d"]   # 辅助周期K线
  start:  # 起始日期 例如"2024-06-01" 默认获取一年
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
    vol: models/model_1h_vol.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
    vol: models/model_4h_vol.pkl
  d1:
    up: models/model_1d_up.pkl
    down: models/model_1d_down.pkl
    vol: models/model_1d_vol.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    # —— 价格 / 动量 ——
    - pct_chg1_1h         # 单根1h涨跌幅:contentReference[oaicite:0]{index=0}
    # —— 震荡 / 振荡 ——
    - cci_delta_1h        # 1h CCI变化率:contentReference[oaicite:1]{index=1}
    # —— 波动率 ——
    - atr_pct_ratio_1h_4h # 1h vs 4h波动率比:contentReference[oaicite:2]{index=2}
    # —— 成交量 / 资金流 ——
    - obv_delta_1h        # 1h OBV变化:contentReference[oaicite:3]{index=3}
    # —— 蜡烛形态 ——
    - upper_wick_ratio_1h # 1h上影线比例:contentReference[oaicite:4]{index=4}

  4h:
    # —— 价格 / 动量 ——
    - pct_chg6_4h         # 最近6根4h涨跌幅:contentReference[oaicite:5]{index=5}
    # —— 震荡 / 振荡 ——
    - rsi_slope_4h        # 4h RSI斜率:contentReference[oaicite:6]{index=6}
    # —— 波动率 ——
    - atr_chg_4h          # 4h ATR变化率:contentReference[oaicite:7]{index=7}
    # —— 成交量 / 情绪 ——
    - vol_roc_4h          # 4h成交量环比增速:contentReference[oaicite:8]{index=8}
    # —— 蜡烛形态 ——
    - upper_wick_ratio_4h # 4h上影线比例:contentReference[oaicite:9]{index=9}

  1d:
    # —— 价格 / 动量 ——
    - pct_chg6_d1         # 最近6日涨跌幅:contentReference[oaicite:10]{index=10}
    # —— 震荡 / 振荡 ——
    - macd_signal_d1      # 日线MACD信号线:contentReference[oaicite:11]{index=11}
    # —— 波动率 ——
    - atr_pct_d1          # 日线ATR百分比:contentReference[oaicite:12]{index=12}
    # —— 宏观 / 链上 ——
    - cg_market_cap_roc_d1# 日级链上市值环比:contentReference[oaicite:13]{index=13}
    # —— 蜡烛形态 ——
    - lower_wick_ratio_d1 # 日线下影线比例:contentReference[oaicite:14]{index=14}

train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
