binance:
  api_key: "${BINANCE_API_KEY}"
  api_secret: "${BINANCE_API_SECRET}"
  proxy:
    http:  "http://127.0.0.1:7890"
    https: "http://127.0.0.1:7890"

coingecko:
  api_key: "${COINGECKO_API_KEY}"  # 可为空或填写公共 API 密钥

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "${MYSQL_PASSWORD}"
  database: "quant_trading"
  charset: "utf8mb4"

data_loader:
  topn: 100             # 获取成交额排名前N的合约
  interval: "1h"       # 主周期K线
  aux_interval: ["4h", "1d"]   # 辅助周期K线
  start:  # 起始日期 例如"2024-06-01" 默认获取一年
  end:     # 结束日期
  cache_dir: "data/klines"
  sentiment_cache: "data/sentiment"
  rate_limit_sleep: 0.05   # 每次请求后休息 50ms，1s 20 次 ≪ 2400/min
  excluded_list: [""]

feature_engineering:
  cache_dir: "data/klines"
  merged_dir: "data/merged"
  merged_table_path: "data/merged/merged_table.csv"
  feature_cols_path: "data/merged/feature_cols.txt"
  topn: 100
  mode: train                        # train 或 inference
  scaler_path: scalers/all_features_scaler.json

feature_selector:
  target: target_up   # 也可换 target_up
  top_n: 100             # 每周期保留前 N

models:
  1h:
    up: models/model_1h_up.pkl
    down: models/model_1h_down.pkl
    vol: models/model_1h_vol.pkl
  4h:
    up: models/model_4h_up.pkl
    down: models/model_4h_down.pkl
    vol: models/model_4h_vol.pkl
  d1:
    up: models/model_1d_up.pkl
    down: models/model_1d_down.pkl
    vol: models/model_1d_vol.pkl

database:
  uri: "mysql+pymysql://user:pwd@host:3306/quant_trading"

feature_cols:
  1h:
    - pct_chg1_1h
    - atr_pct_1h
    - hour_of_day
    - bid_ask_spread_pct_1h
    - volume_cg_ratio_1h
    - long_upper_shadow_1h
    - long_lower_shadow_1h
    - fg_index_feat
    - cci_delta_1h
    - vol_breakout_1h
    - bull_streak_1h
    - rsi_slope_1h
    - atr_pct_ratio_1h_4h
    - price_ratio_cg_1h
    - vol_ma_ratio_long_1h
    - bear_streak_1h
    - adx_delta_1h
    - supertrend_dir_1h
    - hv_7d_1h
    - obv_delta_1h

  4h:
    - vol_roc_4h
    - atr_pct_4h
    - close_spread_1h_4h
    - pct_chg3_4h
    - volume_cg_ratio_4h
    - lower_wick_ratio_4h
    - bid_ask_spread_pct_4h
    - hv_14d_4h
    - cci_delta_4h
    - bb_width_d1
    - vol_breakout_4h
    - adx_delta_d1
    - body_ratio_1h
    - hv_7d_4h
    - bull_streak_4h

  1d:
    - cg_total_volume_roc_d1
    - cg_market_cap_roc_d1
    - price_ratio_cg_1h
    - pct_chg3_d1
    - atr_chg_d1
    - supertrend_dir_d1
    - ema_diff_d1
    - kurtosis_1h
    - macd_d1
    - skewness_d1

train_settings:
  by_symbol: false
  min_rows: 500
  time_ranges: []
